<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Per-user weekly study plan generated by the LLM after onboarding. Spec §21.
 * Schema is intentionally narrow — most of the variability lives inside plan_json
 * so we can iterate on the prompt without migrating tables.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('user_plans', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->timestamp('generated_at');
            $table->string('trainer_id', 16)->nullable();
            $table->integer('elo_at_generation')->nullable();
            $table->json('intents_json')->nullable();
            $table->json('plan_json');
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'generated_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('user_plans');
    }
};
